[package]
name = "pyroxene"
version = "0.1.0"
authors = ["Austin Johnson <me@austinj.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
basalt = { path = "../basalt" }
shellexpand = "2.0.0"
strsim = "0.10.0"
